node:
  endpoint: "NODE_ENDPOINT"
  token-required: false
  token: ""

database:
  endpoint-with-creds: "POSTGRESQL_DATABASE ENDPOINT"
  database-name: ""

slack:
  bot-token: "SLACK_BOT_TOKEN"
  signing-secret: "SLACK_BOT_SIGNING_SECRET"
